### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Fra298** [Nightprince/Yekta-Cms#3]
```
When finishing install I've got an error message : 
```

"Warning: mysqli::query(): MySQL server has gone away in.... /system.php on line 287" 

This is not a big deal as everything's seems to be correctly installed. Just reporting it in case somebody else has same problem.

**Comment by Nightprince** [comment]
direction www.url.com/install/en/system.php ?

**Comment by Fra298** [comment]
yes

**Comment by Nightprince** [comment]
tested . don't have problem . if your database have table , first clean database and again install .
